
export default{
    user: require('../Assets/Images/profile.png'),
    newsfeed: require('../Assets/Images/news.png'),
    video: require('../Assets/Images/video.png'),
    community: require('../Assets/Images/community.png'),
    cloud: require('../Assets/Images/cloud.png'),
    camera: require('../Assets/Images/colorCamera.png'),
    imagePost: require('../Assets/Images/imagePost.png'),
    poll: require('../Assets/Images/poll.png'),
    like: require('../Assets/Images/likes.png'),
    love: require('../Assets/Images/love.png'),
    comment: require('../Assets/Images/comment.png'),
    explore: require('../Assets/Images/exploreIcon.png'),
    activities: require('../Assets/Images/destinations.png'),
    mybookings: require('../Assets/Images/booking.png'),
    location: require('../Assets/Images/location.png'),
    timeOpen: require('../Assets/Images/timeOpen.png'),
    language: require('../Assets/Images/language.png'),
    checkIn: require('../Assets/Images/checkIn.png'),
    cancel : require('../Assets/Images/cancel.png'),
    check : require('../Assets/Images/check.png'),
    message: require('../Assets/Images/messageCopy.png'),
    additionalInfo: require('../Assets/Images/additionalInfo.png'),
    caratIcon: require('../Assets/Images/caratIconCopy3.png'),
    payment: require('../Assets/Images/payment.png'),
    promotion: require('../Assets/Images/promotionCode.png'),
    accountSetting: require('../Assets/Images/accountSettings.png'),
    helpCenter: require('../Assets/Images/helpCenter.png'),
    logOut: require('../Assets/Images/logOut.png'),
    startup: require('../Assets/Images/startup.jpg'),
    startup2: require('../Assets/Images/startup2.jpg'),
    logostartup: require('../Assets/Images/logostartup.png'),
    curatedByMillennia: require('../Assets/Images/curatedByMillennia.png'),
    badgerLogo: require('../Assets/Images/badgerLogo.png'),
    edit: require('../Assets/Images/edit.png')

  }
