 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelApp' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
  ]
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
